#!/bin/bash

set -e

location=/usr/local/apache2/htdocs/wvr-components/bundle/config.json

eval "cat << EOF | tee $location
$(<tmp/config-template.json)
EOF"

echo "Done docker-entrypoint..."

exec "$@"
