#!/bin/bash

set -e
#/usr/local/apache2/htdocs/wvr-components/
versionLocation=./dist/bundle/1x/config.json
latestLocation=./dist/bundle/latest/config.json

eval "cat << EOF | tee $versionLocation $latestLocation
$(<src/config-template.json)
EOF"

echo "Done docker-entrypoint..."

exec "$@"
