export const wvrThemeInputs: Array<string> = [
  'theme',
  'blue',
  'indigo',
  'purple',
  'pink',
  'red',
  'orange',
  'yellow',
  'green',
  'teal',
  'cyan',
  'white',
  'gray',
  'grayDark',
  'primary',
  'secondary',
  'success',
  'info',
  'warning',
  'danger',
  'light',
  'dark',
  'breakpointXs',
  'breakpointSm',
  'breakpointMd',
  'breakpointLg',
  'breakpointXl',
  'fontFamilySansSerif',
  'fontFamilyMonospace'
];

export const wvrThemeHostBindings: any = {
  '[style.--wvr-blue]': 'blue',
  '[style.--wvr-indigo]': 'indigo',
  '[style.--wvr-purple]': 'purple',
  '[style.--wvr-pink]': 'pink',
  '[style.--wvr-red]': 'red',
  '[style.--wvr-orange]': 'orange',
  '[style.--wvr-yellow]': 'yellow',
  '[style.--wvr-green]': 'green',
  '[style.--wvr-teal]': 'teal',
  '[style.--wvr-cyan]': 'cyan',
  '[style.--wvr-white]': 'white',
  '[style.--wvr-gray]': 'gray',
  '[style.--wvr-gray-dark]': 'grayDark',
  '[style.--wvr-primary]': 'primary',
  '[style.--wvr-secondary]': 'secondary',
  '[style.--wvr-success]': 'success',
  '[style.--wvr-info]': 'info',
  '[style.--wvr-warning]': 'warning',
  '[style.--wvr-danger]': 'danger',
  '[style.--wvr-light]': 'light',
  '[style.--wvr-dark]': 'dark',
  '[style.--wvr-breakpoint-xs]': 'breakpointXs',
  '[style.--wvr-breakpoint-sm]': 'breakpointSm',
  '[style.--wvr-breakpoint-md]': 'breakpointMd',
  '[style.--wvr-breakpoint-lg]': 'breakpointLg',
  '[style.--wvr-breakpoint-xl]': 'breakpointXl',
  '[style.--wvr-font-family-sans-serif]': 'fontFamilySansSerif',
  '[style.--wvr-font-family-monospace]': 'fontFamilyMonospace'
};
