name: Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Node Cache"
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: "Node Cache Modules"
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-node_modules-${{ hashFiles('**/package.json', '**/package-lock.json') }}

      - name: "Set up chrome browser"
        # uses: actions/checkout@master
        # uses: nanasess/setup-chromedriver@master
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: "Install Node"
        run: npm install

      - name: "Node Tests"
        run: |
          npm run build
          npm run test:ci
          npm run test:report
          npm run build:static-production

      - name: setup
        run: |
          sudo apt-get -yqq install chromium-chromedriver
          google-chrome --version
          sudo pip3 install selenium
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
          python3 $GITHUB_WORKSPACE/__tests__/chromedriver.py

      - name: "Send to Coveralls (build node-${{ github.run_number }})"
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.github_token }}
          path-to-file: './coverage/coveralls.json'
          coverage-format: raw
